Upload caching files to AWS S3 bucket
codemagic-ci-cd/codemagic-docs pull request #1150
Opened 2022-11-10 15:19 UTC by codemagic-mohammed

2022-11-11 08:44 UTC, nevercode-kevin requested changes

2022-11-11 08:44 UTC, nevercode-kevin commented on content/knowledge-others/install-unity-version.md
> +In order to use AWS S3, you need to configure your access credentials in Codemagic. You can follow the [instructions](https://aws.amazon.com/getting-started/hands-on/backup-to-s3-cli/) provided by Am
```suggestion
In order to use AWS S3, you need to configure your access credentials in Codemagic. You can follow the [instructions](https://aws.amazon.com/getting-started/hands-on/backup-to-s3-cli/) provided by Amazon to create your account and get the necessary credentials.
```

2022-11-11 08:44 UTC, nevercode-kevin commented on content/knowledge-others/install-unity-version.md
> +      sudo pip3 install awscli --upgrade
AWS cli 2.8.9 is pre-installed, so shouldn't need to be upgraded for S3 uploads.

2022-11-11 08:44 UTC, nevercode-kevin commented on content/knowledge-others/install-unity-version.md
> +    fi
Should this be done at the end of the workflow, in the Publishing section scripts, if required?

2023-05-19 10:47 UTC, kevin-suhajda approved these changes
LGTM

2023-05-19 10:47 UTC, merged