Feature: optional remote access
codemagic-ci-cd/codemagic-docs pull request #1179
Opened 2022-11-22 11:24 UTC by artemii-yanushevskyi

Remote access is now only available when requested

2022-11-22 14:58 UTC, helinanever requested changes

2022-11-23 11:20 UTC, mikhail-tokarev requested changes

2022-11-23 11:20 UTC, mikhail-tokarev commented on content/troubleshooting/accessing-builder-machine-via-ssh.md
> +2. Check **Enable remote access** checkbox in the **Start new build modal**.
rename it

2022-11-23 12:54 UTC, mikhail-tokarev approved these changes
LGTM

2022-11-23 13:46 UTC, merged