Updating changeset condition
codemagic-ci-cd/codemagic-docs pull request #1207
Opened 2022-12-02 12:19 UTC by icarusdust

2022-12-02 12:55 UTC, mikhail-tokarev requested changes

2022-12-02 13:01 UTC, icarusdust commented on content/yaml-running-builds/starting-builds-automatically.md
> +Builds will be skipped only after having one successful build since `changeset` setting is configured in `codemagic.yaml`.
I meant to remove that sentence, I missed it.

2022-12-02 13:04 UTC, icarusdust commented on content/yaml-running-builds/starting-builds-automatically.md
> +Using `changeset` setting. you can avoid unnecessary builds when functional components of your repository were not modified. After `changeset` setting is configured in `codemagic.yaml`, the subsequen
Added it as a note, what do you think ?

2022-12-16 12:08 UTC, mikhail-tokarev approved these changes
🚀

2022-12-16 12:09 UTC, merged