Uploading dSYM to correct path with native apps
codemagic-ci-cd/codemagic-docs pull request #1411
Opened 2023-02-17 07:47 UTC by icarusdust

2023-02-28 14:46 UTC, nevercode-kevin requested changes

2023-02-28 14:46 UTC, nevercode-kevin commented on content/knowledge-firebase/firebase-crashlytics-dsym-uploading.md
> +The above-mentioned **dsymPath** is Flutter specific and it could change depending on what platform the app is built. E.g., for React Native or Native iOS applications you might use the dsymPath as:
```suggestion
The above-mentioned **dsymPath** is Flutter-specific and could change depending on what platform the app is built on. For example, in React Native or Native iOS applications you might use the dsymPath as:
```

2023-02-28 15:04 UTC, icarusdust commented on content/knowledge-firebase/firebase-crashlytics-dsym-uploading.md
> +The above-mentioned **dsymPath** is Flutter specific and it could change depending on what platform the app is built. E.g., for React Native or Native iOS applications you might use the dsymPath as:
Done!

2023-03-14 09:22 UTC, nevercode-kevin approved these changes
LGTM

2023-03-14 09:22 UTC, merged