Updating post-processing info
codemagic-ci-cd/codemagic-docs pull request #1737
Opened 2023-06-02 12:27 UTC by icarusdust

2023-06-02 12:33 UTC, kevin-suhajda requested changes

2023-06-02 12:33 UTC, kevin-suhajda commented on content/yaml-publishing/app-store-connect.md
> +Please note that publishing to App Store Connect through **app_specific_password** has been deprecated and Post-processing action will not be triggered unless using the new way of publishing as expla
```suggestion
Please note that publishing to App Store Connect through **app_specific_password** has been deprecated and post-processing actions will not be triggered unless using the new way of publishing as explained above.
```

2023-06-02 12:36 UTC, icarusdust commented on content/yaml-publishing/app-store-connect.md
> +Please note that publishing to App Store Connect through **app_specific_password** has been deprecated and Post-processing action will not be triggered unless using the new way of publishing as expla
done

2023-06-05 07:45 UTC, kevin-suhajda approved these changes
LGTM

2023-06-05 07:48 UTC, merged