Ionic documentation added
codemagic-ci-cd/codemagic-docs pull request #188
Opened 2020-10-04 14:42 UTC by nevercode-kevin

Proposed documentation for building **Ionic Capacitor** and **Ionic Cordova** apps.

2020-10-04 15:59 UTC, VeArnold commented
Might be better to change instance type to mac mini? If users do not pay enough attention, then might cause issues :)

2020-10-06 07:57 UTC, helinanever requested changes

2020-10-06 07:57 UTC, helinanever commented on content/getting-started/building-an-ionic-app.md
> +    * See the full Android workflow example [below](#android-workflow-example).
Should be something along the lines of "See the full workflow examples below" and no link.

2020-10-06 07:57 UTC, helinanever commented on content/getting-started/building-an-ionic-app.md
> +
the link should be: ../publishing-yaml/distribution/

2020-10-06 07:57 UTC, helinanever commented on content/getting-started/building-an-ionic-app.md
> +            #     keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $CM_CERTIFICATE_PASSWORD
I know you want to explicitly show two code signing options but having the two options in the file and some lines marked as commentary creates a lot of noise and makes the file difficult to read

2020-10-06 07:57 UTC, helinanever commented on content/getting-started/building-an-ionic-app.md
> +            #     keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $CM_CERTIFICATE_PASSWORD
Same comment here about code signing

2020-10-06 11:34 UTC, helinanever approved these changes
LGTM

2020-10-06 12:54 UTC, merged