Update flutter-projects.md
codemagic-ci-cd/codemagic-docs pull request #2066
Opened 2023-09-22 12:05 UTC by martinjeret

I got feedback from user trying to search docs and couldn't find possibility to change flutter version in the workflow editor. He could find it in .yaml or fvm, but not in workflow editor. 

Hence made this PR to make it easier to read setting flutter version

2023-09-22 12:13 UTC, nohli approved these changes
Nice, thanks for adding! 🙏🏽

2023-09-25 11:57 UTC, icarusdust requested changes

2023-09-25 11:57 UTC, icarusdust commented on content/flutter-configuration/flutter-projects.md
> +Setting the Flutter version in workflow editor is possible in the build section of your workfor editor.
typo => workflow

2023-09-25 12:41 UTC, icarusdust approved these changes
LGTM

2023-09-25 12:56 UTC, merged