Certificate will no longer be valid in 30 days
codemagic-ci-cd/codemagic-docs pull request #2077
Opened 2023-09-27 13:28 UTC by dtrdic

2023-09-28 09:00 UTC, icarusdust requested changes

2023-09-28 09:00 UTC, icarusdust commented on content/troubleshooting/common-ios-issues.md
> +There's no need to worry, as Codemagic will automatically renew your current certificate. You won't have to generate one manually or replace the old one.
Using CSI won't create resources. Explain what will happen in case of automatiic and manual signing.

2023-10-13 11:33 UTC, dtrdic commented
This is how it looks on UI

![image](https://github.com/codemagic-ci-cd/codemagic-docs/assets/38918425/28d87cf5-5c4d-463b-b3d6-cdd5d093d580)

2023-10-16 08:38 UTC, icarusdust requested changes

2023-10-16 08:38 UTC, icarusdust commented on content/troubleshooting/common-ios-issues.md
> +     If you want to use a specific certificate with CSI, you'll need to provide its private RSA key associated with an iOS Distribution certificate that has previously been generated within your Appl
providing RSA key is not needed when using CSI, it is necessary when using automatic signing.

2023-10-16 08:38 UTC, icarusdust commented on content/troubleshooting/common-ios-issues.md
> + - If you're using `automatic code signing`, Codemagic takes care of certificate and provisioning profile management for you. This means it also automatically renews the certificate when it's about t
Let's explain it sth like this way:

_By providing api key, issuer id etc. Codemagic can take care of........_

2023-10-17 06:45 UTC, icarusdust requested changes

2023-10-17 06:45 UTC, icarusdust commented on content/troubleshooting/common-ios-issues.md
> + - By providing your **App Store Connect API key ID**, **issuer ID**, and API key as a **.p8 file**, Codemagic takes care of your certificate and provisioning profile management, including the automa
Perhaps sth like:

By providing your **App Store Connect API key ID**, **issuer ID**, and API key as a **.p8 file** (_more info about how to add environment variables can be found [here](https://docs.codemagic.io/yaml-basic-configuration/configuring-environment-variables/)_), Codemagic takes care of your certificate and provisioning profile management, including the automatic renewal of certificates unless you are using a private RSA key associated with an iOS Distribution certificate that has previously been generated within your Apple Developer Program account. You can find additional information on how to update an RSA key (CERTIFICATE_PRIVATE_KEY) for a certificate [here](https://docs.codemagic.io/yaml-code-signing/alternative-code-signing-methods/#:~:text=Obtaining%20the%20Certificate%20private%20key).

2023-10-17 07:03 UTC, icarusdust approved these changes
LGTM

2023-10-17 07:09 UTC, merged