Improvement: use x86_64 Unity for both Apple Silicon and Intel processors
codemagic-ci-cd/codemagic-docs pull request #2090
Opened 2023-10-05 14:06 UTC by artemii-yanushevskyi

It's now possible to install and run Unity on Apple Silicon Macs

2023-10-05 14:12 UTC, mikhail-tokarev requested changes

2023-10-05 14:12 UTC, mikhail-tokarev commented on content/knowledge-others/install-unity-version.md
> +Some build machines have Unity pre-installed. Consult build machine specification ([macOS](../specs/versions-macos) and [Windows](../specs/versions-windows)) to find out the version of the pre-instal
```suggestion
```

2023-10-05 14:12 UTC, mikhail-tokarev commented on content/knowledge-others/install-unity-version.md
> +If you need to install or change Unity version, you would need to specify the preferred version in your `codemagic.yaml` file like this:
```suggestion
If you need to install Unity, you would need to specify the preferred version in your `codemagic.yaml` file like this:
```

2023-10-05 14:12 UTC, mikhail-tokarev commented on content/knowledge-others/install-unity-version.md
> +- Mac machines with Apple Silicon support Unity built for `x86_46` architecture.
```suggestion
- Mac machines with Apple silicon support Unity built for `x86_46` architecture.
```

2023-10-06 06:52 UTC, helinanever approved these changes
LGTM

2023-10-06 08:15 UTC, helinanever commented
As I've learned, specifying the Unity version in yaml will not work for Windows. There should be a note about this in docs.

2023-10-06 13:36 UTC, mikhail-tokarev commented on content/knowledge-others/install-unity-version.md
> +## Use Codemagic's supported versions (macOS only)
```suggestion
## Quick install (macOS only)
```

2023-10-06 13:37 UTC, mikhail-tokarev commented on content/knowledge-others/install-unity-version.md
> +Intel Mac and Windows machines have Unity pre-installed. It's possible to install other supported Unity versions.
```suggestion
```

2023-10-06 13:38 UTC, mikhail-tokarev commented on content/knowledge-others/install-unity-version.md
> +**The available Unity versions on Mac machines are the following:**
```suggestion
**The available Unity versions are the following:**
```

2023-10-06 13:39 UTC, mikhail-tokarev commented on content/knowledge-others/install-unity-version.md
```suggestion
## Download and install from Unity Hub
```

2023-10-06 13:40 UTC, mikhail-tokarev commented on content/knowledge-others/install-unity-version.md
don't apply just it. It should be for the next line

2023-10-06 13:47 UTC, mikhail-tokarev approved these changes
🚀

2023-10-06 13:51 UTC, merged