docs: add Capawesome Cloud integration
codemagic-ci-cd/codemagic-docs pull request #2503
Opened 2024-05-02 09:26 UTC by robingenz

This PR adds instructions on how to integrate [Capawesome Cloud](https://capawesome.io/cloud/) with Codemagic.

2024-07-03 17:28 UTC, robingenz commented
Is there anything I need to update?

2024-11-07 12:18 UTC, icarusdust requested changes

2024-11-07 12:20 UTC, icarusdust commented on content/integrations/capawesome-cloud-integration.md
> +Make sure to replace `<app-id>` with the ID of your app on Capawesome Cloud and `<path-to-bundle>` with the path to the bundle you want to upload (e.g. `www`).
or remove the e.g. 'www' because as i understand you need to upload ios and android binaries here

2024-11-07 13:05 UTC, robingenz commented on content/integrations/capawesome-cloud-integration.md
> +Make sure to replace `<app-id>` with the ID of your app on Capawesome Cloud and `<path-to-bundle>` with the path to the bundle you want to upload (e.g. `www`).
Thanks for getting back! No, you do not need to upload the Android and iOS binaries. It's not possible to update the native version of an app via live updates. You can only update the web assets of an app. For this reason, `--path` actually refers to the path of the web build (e.g. `www` or `dist`).

2024-11-08 08:50 UTC, icarusdust commented on content/integrations/capawesome-cloud-integration.md
> +Make sure to replace `<app-id>` with the ID of your app on Capawesome Cloud and `<path-to-bundle>` with the path to the bundle you want to upload (e.g. `www`).
thanks for clarifying it.

2024-11-08 08:56 UTC, icarusdust commented on content/integrations/capawesome-cloud-integration.md
> +Make sure to replace `<app-id>` with the ID of your app on Capawesome Cloud and `<path-to-bundle>` with the path to the bundle you want to upload (e.g. `www`).
I added a note in the sample project demo project, after making these changes,  it looks good to be merged.

2024-11-09 13:11 UTC, robingenz commented on content/integrations/capawesome-cloud-integration.md
> +Make sure to replace `<app-id>` with the ID of your app on Capawesome Cloud and `<path-to-bundle>` with the path to the bundle you want to upload (e.g. `www`).
Yes, I've just made the changes.

2024-11-14 08:36 UTC, icarusdust approved these changes

2024-11-14 08:36 UTC, merged