Add documentation for React Native tests
codemagic-ci-cd/codemagic-docs pull request #315
Opened 2021-04-23 11:21 UTC by SnehPandya18

2021-04-23 12:22 UTC, nevercode-kevin requested changes
The Codemagic instance types use underscores not hyphens so "mac-mini or mac-pro for Macintosh instances" should be "mac_mini or mac_pro for macOS instances". Also use "macOS" instead of "Macintosh"

2021-04-23 12:28 UTC, SnehPandya18 commented
> The Codemagic instance types use underscores not hyphens so "mac-mini or mac-pro for Macintosh instances" should be "mac_mini or mac_pro for macOS instances". Also use "macOS" instead of "Macintosh"

The request changes are updated in the latest commit. Please check.

2021-04-23 12:30 UTC, helinanever requested changes
Minor spelling issues

2021-04-23 12:30 UTC, helinanever commented on content/testing-yaml/testing.md
> +`present` is a preset that is used as a base for Jest’s configuration. A preset should point to an npm module that has a `jest-preset.json` or `jest-preset.js` file at the root.
present > preset

2021-04-23 12:30 UTC, helinanever commented on content/testing-yaml/testing.md
> +      instance_type: linux                # specify linux or linux_2 for Linux instances; mac_mini or mac_pro for MacOS instances
MacOS > macOS

2021-04-23 12:30 UTC, helinanever commented on content/testing-yaml/testing.md
> +Once it done, `wdio.conf` file will be generated inside the `tests` directory.
Once it done > Once it's done

2021-04-23 12:30 UTC, helinanever commented on content/testing-yaml/testing.md
> +      instance_type: linux                # specify linux or linux_2 for Linux instances; mac_mini or mac_pro for MacOS instances
MacOS > macOS

2021-04-23 15:29 UTC, SnehPandya18 commented
> Minor spelling issues

Thanks for pointing out. The spellings are corrected.

2021-04-23 15:37 UTC, helinanever approved these changes
LGTM

2021-04-26 10:51 UTC, nevercode-kevin approved these changes

2021-04-26 10:53 UTC, merged