Improvement: publishing scripts
codemagic-ci-cd/codemagic-docs pull request #347
Opened 2021-05-17 10:18 UTC by artemii-yanushevskyi

2021-05-17 13:30 UTC, helinanever commented on content/getting-started/yaml.md
> +Unlike the scripts run in the scripts section before the publishing step, the post-publish scripts are run regardless of the status of previous scripts.
let's move this right after the intro paragraph for ### Publishing

2021-05-17 16:10 UTC, helinanever requested changes

2021-05-17 16:10 UTC, helinanever commented on content/getting-started/yaml.md
> +
This requires some explanation here, e.g.:
You can also use the post-publishing scripts to report build status.

2021-05-18 06:47 UTC, helinanever approved these changes
LGTM

2021-05-18 07:02 UTC, mikhail-tokarev requested changes

2021-05-18 08:56 UTC, helinanever commented on content/getting-started/yaml.md
> +Note that in this example the `SUCCESS` file will not be created if some build step failed. We it's only used to distinguish between failed and successfull builds.
```suggestion
Note that in this example the `SUCCESS` file will not be created if some build step failed. It is only used to distinguish between failed and successful builds. 
```

2021-05-18 08:56 UTC, helinanever commented on content/getting-started/yaml.md
> +Unlike the scripts run in the scripts section before the publishing step, the post-publish scripts are run regardless of the status of previous scripts.
```suggestion
Unlike the scripts run in the scripts section before the publishing step, the publishing scripts are run regardless of the status of previous scripts.
```

2021-05-18 09:08 UTC, merged