Native -ios - Env variable groups
codemagic-ci-cd/codemagic-docs pull request #511
Opened 2021-09-20 04:16 UTC by K-Codemagic

2021-09-21 12:32 UTC, nevercode-kevin requested changes

2021-09-21 12:32 UTC, nevercode-kevin commented on content/yaml-quick-start/building-a-native-ios-app.md
> +        apple_id: $APPLE_ID
use new publishing method

2021-09-21 12:32 UTC, nevercode-kevin commented on content/yaml-quick-start/building-a-native-ios-app.md
> +        password: $APP_SPECIFIC_PASSWORD
use new publishing method
```suggestion
                    app_store_connect:   # https://docs.codemagic.io/publishing-yaml/distribution              
              api_key: $APP_STORE_CONNECT_PRIVATE_KEY         # Contents of the API key, can also reference environment variable such as $APP_STORE_CONNECT_PRIVATE_KEY
              key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER       # Alphanumeric value that identifies the API key, can also reference environment variable such as $APP_STORE_CONNECT_KEY_IDENTIFIER
              issuer_id: $APP_STORE_CONNECT_ISSUER_ID         # Alphanumeric value that identifies who created the API key, can also reference environment variable such as $APP_STORE_CONNECT_ISSUER_ID
              submit_to_testflight: false                     # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight beta review. Required for distributing to beta groups. Note: This action is performed during post-processing.
            # beta_groups:                                  # Specify the names of beta tester groups that will get access to the build once it has passed beta review. 
            #       - group name 1
            #       - group name 2
```

2021-09-21 12:32 UTC, nevercode-kevin commented on content/yaml-quick-start/building-a-native-ios-app.md
> +      groups:
add env group for ios credentials for publishing

2021-09-22 09:28 UTC, K-Codemagic commented on content/yaml-quick-start/building-a-native-ios-app.md
> +        password: $APP_SPECIFIC_PASSWORD
Changes have been made

2021-09-22 09:40 UTC, nevercode-kevin requested changes
Set `submit_to_testflight: false` otherwise it will expect the beta_groups to be available.

2021-09-22 09:40 UTC, nevercode-kevin commented on content/yaml-quick-start/building-a-native-ios-app.md
> +        submit_to_testflight: true        # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight to automatically enroll your build to beta testers.
```suggestion
        submit_to_testflight: false        # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight to automatically enroll your build to beta testers.
```

2021-09-22 09:46 UTC, nevercode-kevin approved these changes
LGTM

2021-09-22 09:51 UTC, nevercode-kevin requested changes

2021-09-22 09:51 UTC, nevercode-kevin commented on content/yaml-quick-start/building-a-native-ios-app.md
> +        - app_store_credentials # <-- Include - APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY
```suggestion
        - app_store_credentials # <-- Includes: APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY
```

2021-09-22 09:51 UTC, nevercode-kevin commented on content/yaml-quick-start/building-a-native-ios-app.md
> +        - certificate_credentials # <-- Include - CERTIFICATE_PRIVATE_KEY
```suggestion
        - certificate_credentials # <-- Includes: CERTIFICATE_PRIVATE_KEY
```

2021-09-23 07:07 UTC, nevercode-kevin approved these changes
LGTM

2021-09-23 07:08 UTC, merged