Create accessing-git-lfs.md
codemagic-ci-cd/codemagic-docs pull request #523
Opened 2021-09-21 20:01 UTC by icarusdust

How to access Git LFS

2021-09-22 06:50 UTC, helinanever commented on content/knowledge-base/accessing-git-lfs.md
> +description: How to use git lfs with codemagic
```suggestion
description: How to use Git LFS with Codemagic
```

2021-09-22 06:51 UTC, helinanever commented on content/knowledge-base/accessing-git-lfs.md
> +  - '../custom-scripts/accessing-git-lfs'
no aliases are needed for this page

2021-09-22 06:51 UTC, helinanever commented on content/knowledge-base/accessing-git-lfs.md
> +
unnecessary empty row

2021-09-22 06:51 UTC, helinanever commented on content/knowledge-base/accessing-git-lfs.md
> +In order to access Git LFS (an open-source Git extension for versioning large files) during a build, add `git lfs install --skip-smudge` in a post-clone script.
maybe a couple of words where the script needs to be added in flutter workflow editor vs yaml?

2021-09-22 06:52 UTC, helinanever requested changes
I've left some comments

2021-11-29 13:07 UTC, icarusdust commented
Changes made!

2021-11-29 15:39 UTC, nevercode-kevin approved these changes
LGTM

2021-11-29 15:43 UTC, merged