Update browserstack-integration.md
codemagic-ci-cd/codemagic-docs pull request #583
Opened 2021-10-28 14:01 UTC by icarusdust

2021-11-26 17:01 UTC, nevercode-kevin requested changes

2021-11-26 17:01 UTC, nevercode-kevin commented on content/integrations/browserstack-integration.md
> +**$BROWSERSTACK_USERNAME** and **$BROWSERSTACK_ACCESS_TOKEN** are generated to you automatically after signing up with **BrowserStack** and setting up the environment variables in the Codemagic UI wi
```suggestion
**BROWSERSTACK_USERNAME** and **BROWSERSTACK_ACCESS_TOKEN** are generated for you automatically after signing up with **BrowserStack**. Adding these as environment variables in the Codemagic UI will allow them to be used during a build.
```

2021-11-29 08:02 UTC, icarusdust commented
Thanks Kevin, changes made.

2021-11-29 08:34 UTC, nevercode-kevin approved these changes
LGTM

2021-11-29 10:57 UTC, merged