Update building-a-native-ios-app.md
codemagic-ci-cd/codemagic-docs pull request #586
Opened 2021-11-03 19:46 UTC by icarusdust

2021-11-26 17:07 UTC, nevercode-kevin requested changes

2021-11-26 17:07 UTC, nevercode-kevin commented on content/yaml-quick-start/building-a-native-ios-app.md
> +    react-native-ios:
```suggestion
    simulator-native-ios:
```

2021-11-26 17:07 UTC, nevercode-kevin commented on content/yaml-quick-start/building-a-native-ios-app.md
> +                npm install
Not required in a native ios project.

2021-11-29 08:04 UTC, icarusdust commented
Done!

2021-11-29 08:36 UTC, nevercode-kevin requested changes

2021-11-29 08:36 UTC, nevercode-kevin commented on content/yaml-quick-start/building-a-native-ios-app.md
> +            node: v16.11.1
Not required for native iOS build.

2021-11-29 11:56 UTC, nevercode-kevin requested changes

2021-11-29 11:56 UTC, nevercode-kevin commented on content/yaml-quick-start/building-a-native-ios-app.md
> -            node: v16.11.1
Only need to delete `node: v16.11.1`

2021-11-29 12:37 UTC, nevercode-kevin approved these changes
LGTM

2021-11-29 12:39 UTC, merged