Add windows documentation
codemagic-ci-cd/codemagic-docs pull request #590
Opened 2021-11-11 12:34 UTC by VeArnold

2021-11-12 16:28 UTC, helinanever commented on content/flutter-configuration/flutter-projects.md
note about Windows machines missing

2021-11-15 09:21 UTC, helinanever commented on content/knowledge-base/partner-center-authentication.md
> +description: How to set up a service account for authentication with Google Play and Firebase
this needs to be changed

2021-11-15 09:23 UTC, helinanever commented on content/yaml-publishing/distribution.md
> +Codemagic enables you to automatically publish your desktop app to the Microsoft Store. Note that a prior successful submission has to have been made through the Partner Center in order for Codemagic
```suggestion
Codemagic enables you to automatically publish your Windows desktop app to the Microsoft Store. Note that a prior successful submission through the Partner Center is required for Codemagic to be able to publish your application.
```

2021-11-15 09:23 UTC, helinanever commented on content/yaml-publishing/distribution.md
> +Codemagic enables you to automatically publish your desktop app to the Microsoft Store. Note that a prior successful submission has to have been made through the Partner Center in order for Codemagic
Add the same note here too that the msix package can be downloaded from build artifacts and uploaded manually

2021-11-15 09:25 UTC, helinanever commented on content/yaml-publishing/distribution.md
> +For publishing, Codemagic makes use of the [Microsoft Store submission API](https://docs.microsoft.com/en-us/windows/uwp/monetize/create-and-manage-submissions-using-windows-store-services). Thus it
```suggestion
For publishing, Codemagic makes use of the [Microsoft Store submission API](https://docs.microsoft.com/en-us/windows/uwp/monetize/create-and-manage-submissions-using-windows-store-services). This requires linking your Partner Center account to the Azure AD application and providing Codemagic with information that can be used to generate temporary Azure AD access tokens for managing submissions.
```

2021-11-15 09:26 UTC, helinanever commented on content/yaml-publishing/distribution.md
> +To get the necessary details (`tenant_id`, `client_id`, `client_secret`), follow the instructions [here](../knowledge-base/partner-center-authentication).
```suggestion
To link your Microsoft Partner Center account with the Azure AD application and get the necessary details (`tenant_id`, `client_id`, `client_secret`), follow the instructions [here](../knowledge-base/partner-center-authentication).
```

2021-11-15 09:28 UTC, helinanever commented on content/yaml-publishing/distribution.md
> +It is also necessary for you to provide your `store_id`, which can be found in the [Partner Center apps dashboard URL](https://partner.microsoft.com/en-us/dashboard/apps), when looking at the details
```suggestion
It is also necessary for you to provide your `store_id`, which can be found when you open the application in the [Partner Center apps dashboard](https://partner.microsoft.com/en-us/dashboard/apps).

2021-11-15 09:29 UTC, helinanever commented on content/yaml-publishing/distribution.md
> +To safely store and use the `client_secret`, configure it as an [environment variables](/variables/environment-variable-groups/#storing-sensitive-valuesfiles) in Codemagic. Click **Secure** to encryp
```suggestion
To safely store and use the `client_secret`, save it as an [environment variable](/variables/environment-variable-groups/#storing-sensitive-valuesfiles) in the Codemagic UI. Click **Secure** to encrypt the value.
```

2021-11-15 09:31 UTC, helinanever commented on content/yaml-quick-start/building-a-flutter-app.md
> +{{</notebox>}}
please remove the note

2021-11-15 09:32 UTC, helinanever commented on content/yaml-quick-start/building-a-flutter-app.md
> +        BUNDLE_ID: 'YOUR_BUNDLE_ID_HERE'
just wondering about these changes, could there be a difference between using double and single quotation marks?

2021-11-15 09:32 UTC, helinanever commented on content/yaml-quick-start/building-a-flutter-app.md
> +        channel: '#builds'
here too, double vs single quotation marks

2021-11-15 10:30 UTC, VeArnold commented on content/flutter-publishing/publishing-to-microsoft-store.md
> +4. Enter the **Client ID** related to your application in Azure AD.
I think it's okay if it's in the overall guide in Step 1 to avoid clutter

2021-11-15 10:31 UTC, VeArnold commented on content/flutter-publishing/publishing-to-microsoft-store.md
> +5. Enter the the value of your **Client secret** from your Certificates & secrets section under your application in Azure AD.
Azure AD, and can be required by following step 1

2021-11-15 12:55 UTC, helinanever requested changes

2021-11-15 12:55 UTC, helinanever commented on content/flutter-configuration/flutter-projects.md
> +- Windows builds can be run on Windows build machines
In FWE, we also allow building Android and Web on Windows

2021-11-15 12:55 UTC, helinanever commented on content/flutter-publishing/publishing-to-microsoft-store.md
> +   These values can be found in [Microsoft Partner Center](https://partner.microsoft.com/en-us/dashboard/home), navigating to **Apps and games > [Your application] > Product Identity**.
```suggestion
   These values can be found in [Microsoft Partner Center](https://partner.microsoft.com/en-us/dashboard/home) when navigating to **Apps and games > [Your application] > Product Identity**.
```

2021-11-15 12:55 UTC, helinanever commented on content/yaml-quick-start/building-a-flutter-app.md
> +Codemagic recommends using the [Flutter msix package](https://pub.dev/packages/msix) for packaging the application. In order for the package to be suitable for publishing to Microsoft Store it is nec
```suggestion
Codemagic uses the [Flutter msix package](https://pub.dev/packages/msix) for packaging the application. For publishing to the Microsoft Store, it is necessary to define certain arguments during packaging.
```

2021-11-15 12:55 UTC, helinanever commented on content/yaml-quick-start/building-a-flutter-app.md
> +To pass these arguments to the packaging tool, it is necessary to either add the parameters to the packaging command in `codemagic.yaml` or to add the package to your project prior to using Codemagic
```suggestion
To pass these arguments to the packaging tool, either add the parameters to the packaging command in `codemagic.yaml` or add the package to your project and [configure](https://pub.dev/packages/msix#gear-configuration-optional) the arguments inside the `pubspec.yaml` file.
```

2021-11-15 12:55 UTC, helinanever commented on content/yaml-quick-start/building-a-flutter-app.md
> +For all the possible flags for the `msix:create` command, check the [pub documentation](https://pub.dev/packages/msix#clipboard-available-configuration-fields), as mentioned prior, these parameters c
```suggestion
For all the possible flags for the `msix:create` command, check the [pub documentation](https://pub.dev/packages/msix#clipboard-available-configuration-fields). Note that when configuring the flags both in `codemagic.yaml` and `pubspec.yaml`, the ones configured in `codemagic.yaml` take precedence.
```

2021-11-15 14:17 UTC, helinanever approved these changes
LGTM

2021-11-16 09:33 UTC, merged