Improvements to the API regarding env variables
codemagic-ci-cd/codemagic-docs pull request #603
Opened 2021-11-22 15:20 UTC by VeArnold

Blocked until changes to code.

2021-11-23 11:17 UTC, helinanever commented on content/rest-api/applications.md
> +Codemagic allows you to fetch and modify application variables and secrets using the REST API. Note that these variables are available only for applications using the `codemagic.yaml` file for config
```suggestion
Codemagic allows you to fetch and modify application variables and secrets using the REST API. Note that these variables are available only for the applications that are configured using the `codemagic.yaml` file. For such applications, variables and secrets are manually configured on the **Environment variables** tab in your application settings.

```

2021-11-23 11:17 UTC, helinanever commented on content/rest-api/applications.md
> +#### Curl request
Curl or CURL? see previous sections

2021-11-23 11:19 UTC, helinanever commented on content/rest-api/applications.md
> +Codemagic allows you to fetch and modify application variables and secrets using the REST API. Note that these variables are available only for applications using the `codemagic.yaml` file for config
Perhaps add a link to the env vars doc that explains how the variables are managed in the UI so there's also info about the groups

2021-11-23 11:19 UTC, helinanever commented on content/rest-api/applications.md
> +To successfully add a new variable, it is necessary to provide the values for `key`, `value` and `group` as JSON data. By default the variable is encrypted. Set the value of `secure` to `false` in or
```suggestion
To successfully add a new variable, it is necessary to provide the values for `key`, `value` and `group` as JSON data. By default, the variable is encrypted. Set the value of `secure` to `false` to not encrypt the newly added variable. An example payload:

```

2021-11-23 12:10 UTC, helinanever commented on content/rest-api/teams.md
> +Based on the team id provided, returns the team information.
Returns the team information based on the provided team ID.

2021-11-23 12:11 UTC, helinanever commented on content/rest-api/teams.md
> +Codemagic allows you to fetch and modify global variables and secrets using the REST API. These variables can be manually configured under **Team settings > your team > Global variables and secrets**
```suggestion
Codemagic allows you to fetch and modify global variables and secrets using the REST API. These variables can be manually configured in **Team settings > your team > Global variables and secrets**.
```

2021-11-23 12:11 UTC, helinanever commented on content/rest-api/teams.md
> +To successfully add a new variable, it is necessary to provide the values for `key`, `value` and `group` as JSON data. By default the variable is encrypted. Set the value of `secure` to `false` in or
```suggestion
To successfully add a new variable, it is necessary to provide the values for `key`, `value` and `group` as JSON data. By default, the variable is encrypted. Set the value of `secure` to `false` to not encrypt the newly added variable. An example payload:
```

2021-11-23 12:14 UTC, helinanever reviewed
Added some minor comments about the copy.

2021-11-24 11:27 UTC, helinanever approved these changes
LGTM

2021-11-24 11:58 UTC, mikhail-tokarev requested changes

2021-11-24 11:58 UTC, mikhail-tokarev commented on content/rest-api/applications.md
> +curl -XGET -H 'X-Auth-Token: <API Token>' -H "Content-type: application/json" 'https://api.codemagic.io/apps/<app_id>/variables'
`x-auth-token` in lowercase here and below

2021-11-24 11:58 UTC, mikhail-tokarev commented on content/rest-api/applications.md
> +#### Payload
1. table format is easy to read
2. add about base64 for binary data

2021-11-24 11:58 UTC, mikhail-tokarev commented on content/rest-api/applications.md
> +#### Payload
also replace with section "Parameter" and table

2021-11-24 12:06 UTC, mikhail-tokarev requested changes

2021-11-24 12:06 UTC, mikhail-tokarev commented on content/rest-api/applications.md
> +          "key": "your variable name",
`id` is important but missing in all examples

2021-11-24 12:06 UTC, mikhail-tokarev commented on content/rest-api/applications.md
> +#### CURL request
try to keep the same structure for all new actions. I'd recommend using:
- Parameters
- Example
- Response

2021-11-24 12:36 UTC, mikhail-tokarev requested changes

2021-11-24 12:36 UTC, mikhail-tokarev commented on content/rest-api/applications.md
> +To successfully add a new variable, it is necessary to provide the values for `key`, `value` and `group` as JSON data.
no need to repeat what already marked as `Required` in the table

2021-11-24 12:36 UTC, mikhail-tokarev commented on content/rest-api/applications.md
> +Note that if the group does not exist, it will be created.
move it to the table

2021-11-24 12:36 UTC, mikhail-tokarev commented on content/rest-api/applications.md
> +| `value` | `string` | **Required.** Value of the variable. |
my prev comment about binary data and base64 got lost

2021-11-24 13:00 UTC, mikhail-tokarev requested changes

2021-11-24 13:00 UTC, mikhail-tokarev commented on content/rest-api/applications.md
> +| `value` | `string` | **Required.** Value of the variable. For files base64 encode the contents. |
For binary data use `base64` to encode the contents.

2021-11-24 13:00 UTC, mikhail-tokarev commented on content/rest-api/applications.md
> +To encode file contents and paste result to clipboard
remove it

2021-11-24 13:07 UTC, mikhail-tokarev approved these changes

2021-11-24 13:07 UTC, merged