Update webhooks.md
codemagic-ci-cd/codemagic-docs pull request #616
Opened 2021-12-01 12:08 UTC by icarusdust

2021-12-01 12:13 UTC, icarusdust commented
Fixes #393

2021-12-01 17:12 UTC, nevercode-kevin requested changes

2021-12-01 17:12 UTC, nevercode-kevin commented on content/configuration/webhooks.md
> +
I think that it needs to be two links. 
- One for how to set up triggers in Workflow Editor
- One for how to set it up in codemagic.yaml

2021-12-02 08:19 UTC, icarusdust commented
Added two separate links.

2021-12-02 08:25 UTC, nevercode-kevin approved these changes
LGTM

2021-12-02 08:27 UTC, merged