Update publishing-to-app-store.md
codemagic-ci-cd/codemagic-docs pull request #617
Opened 2021-12-01 12:20 UTC by icarusdust

2021-12-01 12:21 UTC, icarusdust commented
Fixes #299

2021-12-01 17:16 UTC, nevercode-kevin requested changes

2021-12-01 17:16 UTC, nevercode-kevin commented on content/flutter-publishing/publishing-to-app-store.md
> +
```suggestion
In order to be able to test iOS apps on Apple devices, manual device UDID registration in the Apple Developer Program account is required. Alternatively, Codemagic's automatic device registration can be used to register devices as explained [here](https://docs.codemagic.io/testing/ios-provisioning/). 
```

2021-12-01 19:54 UTC, icarusdust commented
Changes made!

2021-12-02 08:01 UTC, nevercode-kevin approved these changes
LGTM

2021-12-02 08:12 UTC, merged