Update builds.md
codemagic-ci-cd/codemagic-docs pull request #680
Opened 2022-01-18 13:09 UTC by icarusdust

2022-01-18 13:11 UTC, icarusdust commented
Fixes #446

2022-01-18 13:35 UTC, VeArnold requested changes

2022-01-18 13:35 UTC, VeArnold commented on content/rest-api/builds.md
> +| `cancelled`   |
use American English in docs

cancelled > canceled

2022-01-18 13:35 UTC, VeArnold commented on content/rest-api/builds.md
> +| **Status**  |
Comprehensive list:
```
    QUEUED = "queued"
    PREPARING = "preparing"
    FETCHING = "fetching"
    TESTING = "testing"
    BUILDING = "building"
    PUBLISHING = "publishing"
    FINISHING = "finishing"

    FINISHED = "finished"
    WARNING = "warning"
    FAILED = "failed"
    CANCELED = "canceled"
    TIMEOUT = "timeout"
    SKIPPED = "skipped"
```

2022-01-18 13:49 UTC, icarusdust commented on content/rest-api/builds.md
> +| **Status**  |
changes made.

2022-01-18 13:51 UTC, mikhail-tokarev commented on content/rest-api/builds.md
> +| **Status**  |
maybe let's sort it by alphabet?

2022-01-18 14:00 UTC, icarusdust commented on content/rest-api/builds.md
> +| **Status**  |
Yes, would be better. Ordered now.

2022-01-19 10:02 UTC, VeArnold approved these changes
LGTM

2022-01-19 10:03 UTC, merged