Steam-deploying
codemagic-ci-cd/codemagic-docs pull request #872
Opened 2022-07-15 12:12 UTC by mohammedbabelly20

2022-07-15 12:18 UTC, VeArnold commented on content/yaml-publishing/steam.md
> +Steamcmd is the tool used to upload builds to Steam. Steamcmd requires logging into Steam and will normally require a Steam Guard code be entered.
in to

2022-07-15 12:19 UTC, VeArnold commented on content/yaml-publishing/steam.md
> +Steamcmd is the tool used to upload builds to Steam. Steamcmd requires logging into Steam and will normally require a Steam Guard code be entered.
SteamCMD?

2022-07-15 12:20 UTC, VeArnold requested changes

2022-07-15 12:20 UTC, VeArnold commented on content/yaml-publishing/steam.md
> +First you need to install the steamcmd.
First, you need to install SteamCMD.

2022-07-15 12:20 UTC, VeArnold commented on content/yaml-publishing/steam.md
> +Warning: When you are base64 encoding the files, make sure to remove the new lines `\n` of the encoded value, before saving it to Codemagic.
value, before (unnecessary comma)

2022-07-15 12:20 UTC, VeArnold commented on content/yaml-publishing/steam.md
> +See the sample project in [here](https://github.com/codemagic-ci-cd/codemagic-sample-projects/tree/main/unity/unity-deploy-steam).
remove "in"

2022-07-15 18:11 UTC, VeArnold requested changes

2022-07-15 18:11 UTC, VeArnold commented on content/yaml-publishing/steam.md
> +SteamCMD is the tool used to upload builds to Steam. SteamCMD requires logging into Steam and will normally require a Steam Guard code be entered.
```suggestion
SteamCMD is a tool used to upload builds to Steam. SteamCMD requires logging in to Steam and typically requires entering a Steam Guard code.
```

2022-07-15 18:11 UTC, VeArnold commented on content/yaml-publishing/steam.md
> +So we are going to save the sentry files as secure environment variables and then place them at the correct path when the build starts.
Thus, we will save the sentry files as secure environment variables and place them at the correct path when the build starts.

2022-07-15 18:11 UTC, VeArnold commented on content/yaml-publishing/steam.md
> +Warning: When you are base64 encoding the files, make sure to remove the new lines `\n` of the encoded value before saving it to Codemagic.
```suggestion
Warning: When base64 encoding the files, make sure to remove the new lines `\n` of the encoded value before saving it to Codemagic. 
```

2022-07-15 18:11 UTC, VeArnold commented on content/yaml-publishing/steam.md
> +These are standard VDF files required for uploading a build to Steam and require your application's AppID, DepotID and branch name for deployment.
```suggestion
These are standard VDF files required for uploading a build to Steam and require your application's AppID, DepotID, and branch name for deployment.
```

2022-07-15 18:12 UTC, VeArnold commented
Can merge after looking over the suggestions. Other than minor changes, LGTM.

2022-07-18 07:15 UTC, codemagic-mohammed commented
> Can merge after looking over the suggestions. Other than minor changes, LGTM.

Ok, I applied the suggested changes, you can accept the PR now so I can merge it.

2022-07-18 08:48 UTC, VeArnold approved these changes
LGTM

2022-07-18 08:49 UTC, merged