sofy documentation
codemagic-ci-cd/codemagic-docs pull request #880
Opened 2022-07-19 13:41 UTC by icarusdust

2022-08-07 08:07 UTC, nevercode-kevin requested changes

2022-08-07 08:07 UTC, nevercode-kevin commented on content/integrations/sofy-integration.md
> +It is possible to publish binaries generated by **Codemagic** and schedule automation tests with **Sofy** via **codemagic.yaml**. More info can be found [here](../yaml/yaml-getting-started/). In orde
```suggestion
It is possible to publish binaries generated by **Codemagic** and schedule automation tests with **Sofy** via **codemagic.yaml**. More info about working with Codemagic's YAML configuration can be found [here](../yaml/yaml-getting-started/). You will need to sign up with [**Sofy**](https://sofy.ai/) so you can obtain an API Key which is required for deploying your apps via **Codemagic**. 
```

2022-08-07 08:07 UTC, nevercode-kevin commented on content/integrations/sofy-integration.md
> +    --form "applicationFile=@"$APK_PATH""
```suggestion
    --form "applicationFile=@'$APK_PATH'"
```

2022-08-07 08:07 UTC, nevercode-kevin commented on content/integrations/sofy-integration.md
> +    "ScheduledID":$SCHEDULE_ID
```suggestion
    "APIKey": "$SOFY_API_KEY",
    "ScheduledID": "$SCHEDULE_ID"
```

2022-08-07 08:07 UTC, nevercode-kevin commented on content/integrations/sofy-integration.md
> +        "ScheduledID":$SCHEDULE_ID
```suggestion
        "APIKey": "$SOFY_API_KEY",
        "ScheduledID": "$SCHEDULE_ID"
```

2022-08-07 08:07 UTC, nevercode-kevin commented on content/integrations/sofy-integration.md
> +**$SOFY_SUBSCRIPTION_KEY**, **ScheduledID** and **$SOFY_API_KEY** are coming from your **Sofy** account settings and can be named to anything preferred. More info can be found [here](https://docs.cod
```suggestion
**$SOFY_SUBSCRIPTION_KEY**, **ScheduledID** and **$SOFY_API_KEY** are coming from your **Sofy** account settings and can be named to anything you prefer. More info can be found [here](https://docs.codemagic.io/variables/environment-variable-groups/) about how to set up environment variable groups with Codemagic. Environment variables can be added in the Codemagic web app using the ‘Environment variables’ tab. You can then import your variable groups into your codemagic.yaml. For example, if you named your variable group ‘sofy_credentials’, you would import it as follows:
```

2022-08-08 13:45 UTC, icarusdust commented
Done

2022-08-08 13:52 UTC, nevercode-kevin requested changes

2022-08-08 14:01 UTC, icarusdust commented on content/integrations/sofy-integration.md
> +    --form "applicationFile=@'$APK_PATH'"
done

2022-08-08 14:02 UTC, nevercode-kevin approved these changes
LGTM

2022-08-08 14:04 UTC, merged